postmanlabs/postman-request

- .gitignore
- README.md
- package-lock.json
- package.json
- request.js
- tests/test-stream.js
This PR adds a package called `stream-length` then uses the same in defer/end function to set content length from the stream if possible. Additional care is taken to not to do this if `content-length` header is set.
> Added support for detecting stream length

- package.json
Fixes https://nodesecurity.io/advisories/525
> Bumped tough-cookie to v2.3.3

- package-lock.json
- request.js
- tests/test-form-data-postman.js
- tests/test-headers.js
When the form-data size is too big, an exception is thrown because of the way an internal module has been written (combined-stream)
This PR adds a temporary patch (a try-catch block) to fix this issue.
@kunagpal ~Builds are failing on master as well.~ It was happening coz of an ipV6 test. Have disabled the test for Travis
> Wrap piping from form-data to request in a try-catch block

- index.js
- lib/helpers.js
- package.json
- tests/test-defaults.js
- tests/test-errors.js
Removes restriction of sending request body using HTTP `HEAD` method.
>  Allow sending request body with HEAD method

- README.md
- lib/redirect.js
- request.js
- tests/test-form-data-array.js
- tests/test-form-data-redirect.js
- tests/test-form-data.js
- Define formData in array representation to preserve the order.
- Supports backward compatibility.
```javascript
formData: [{
key: 'field_name',
value: 'field_value',
options: {...}
}]
```
> Respect form-data fields ordering

- README.md
- lib/redirect.js
- tests/test-follow-auth-header.js
- tests/test-redirect.js
- Handle `Authorization` header on redirects correctly
- Cleanup repetitive logic in `redirect.js`
> Remove authorization header while redirecting to different host

- README.md
- index.js
- request.js
- tests/test-api.js
- tests/test-ssl.js
Add support for extending the root CA certificates.
```javascript
const request = require('postman-request');
// enable this feature
request.enableNodeExtraCACerts();
// request with extra CA certs
request({... extraCA: 'string/buffer'})
// disable this feature
request.disableNodeExtraCACerts()
```
Benchmarks:
```
with options.ca:
keepAlive: true = 1,806 ops/sec ±4.98% (73 runs sampled)
keepAlive: false = 414 ops/sec ±2.02% (75 runs sampled)
with process.env.NODE_EXTRA_CA_CERTS:
keepAlive: true = 2,096 ops/sec ±4.23% (69 runs sampled)
keepAlive: false = 422 ops/sec ±1.73% (77 runs sampled)
with request.enableNodeExtraCACerts():
keepAlive: true = 2,045 ops/sec ±5.20% (69 runs sampled)
keepAlive: false = 331 ops/sec ±5.64% (77 runs sampled)
```
> Added support for extending the root CA certificates

- README.md
- request.js
- tests/test-disablePostmanUrlEncoder.js
Add disablePostmanUrlEncoder option which will prevent postman-url-encoder to encode given URL for the request.
> Add disablePostmanUrlEncoder option

- lib/auth.js
- lib/multipart.js
- lib/redirect.js
- request.js
- tests/test-proxy-connect.js
- tests/test-redirect.js
When setting headers, `postman-request` added headers in lowercase. Change all `setHeader` call header name arguments from lowercase to TitleCase to preserve consistency.
This change does not change case for the headers which are already present in the request/response i.e. if a node sent headers in lowercase, they are kept that way.
> Use Title-Case names when setting headers

- request.js
- tests/test-form-data-boundary.js
`Content-Type` was re-written if `Content-Length` was not present. This change prevents that behaviour. Also adds test for specifying custom charset in the `Content-Type` header.
> Prevent `Content-Type` override if `Content-Length` not set

- request.js
- tests/test-headers.js
Correctly generate `cookie` header if multiple `cookie` headers are present as well as cookies present in the cookie jar.
Previously: `Cookie: c3=v3,c4=v4; c1=v1; c2=v2`
Now: `Cookie: c3=v3; c4=v4; c1=v1; c2=v2`
> Handle multiple `cookie` headers with jar

- package.json
- tests/test-tunnel-response.js
This change updates the tunnel-agent such that it does not throw
assertion error when proxy server sends a response to the CONNECT
request. This also adds tests for this case.
> Fix the crash when proxy server sends a response

- package.json
- tests/test-form-data.js
- https://github.com/postmanlabs/postman-app-support/issues/3742
- https://github.com/postmanlabs/postman-app-support/issues/5912
Updated `form-data` dependency to use our fork `@postman/form-data` with the following changes:
- https://github.com/postmanlabs/form-data/pull/1
- https://github.com/postmanlabs/form-data/pull/2
> Updated form-data dependency

- request.js
- tests/test-form-data-boundary.js
Added an option `allowContentTypeOverride` to allow overriding invalid content-type header for form-data and url-encoded request bodies.
> Added `allowContentTypeOverride` option

- request.js
- tests/raw.file
- tests/test-body.js
Instead of returning the first available type, [mime-types](https://github.com/jshttp/mime-types) simply returns `false`, so fallback to `application/octet-stream`.
> Add fallback for mime.lookup

- request.js
- tests/test-default-headers.js
Add default `Content-Length` header (same as Node.js) for the following methods:
- GET
- HEAD
- TRACE
- DELETE
- CONNECT
- OPTIONS
It also fixes a bug where custom `Content-Length` was not honored for the empty body.
> Add default `Content-Length` header

- README.md
- request.js
- tests/test-agents.js
Added new `agents` options which accept separate agent instance for `http` and `https`.
> Added support for specifying separate agents for HTTP and HTTPS

- README.md
- request.js
- In both Runtime and Postman documentation, type of `validFrom` and `validTo` properties in `debug.session.tls.peerCertificate` object is documented as String. But it was actually returning the Date object instead.
- Fixed the return type of the said properties to match the documentation
> Fix debug info object to return string as per documentation

- request.js
Fixed a bug where proxy URL was parsed at multiple places without unescaping the auth component.
> Fixed encoding of auth component in the proxy url

- request.js
- tests/test-verbose.js
Bug - Debug object did not have correct request headers.
Cause - Request headers reference was being added to _reqResInfo. The request headers are mutated in onRequestResponse to remove the host header to support subsequent calls for redirects. Similar mutation happens for Referer header. This mutates the debug object also.
Solution - Parsed `ClientRequest._header` for request headers and `IncomingMessage.rawHeaders` for response headers.
> Change structure of headers in debug object

- lib/http2/request.js
- request.js
- tests/test-ssl-http2.js
Added try-catch to prevent ERR_HTTP2_SOCKET_UNBOUND from bubbling up. This happens when the main execution tries to remove listeners from the socket, but if the stream has errored out, the socket is disassociated with the session and hence the error.
> Added exception handlers when removing listeners from http2 sockets

- lib/http2/request.js
- request.js
- tests/test-body-http2.js
Added dynamic endstream  parameter to immediately close writable when no data is present
> Added dynamic  endstream 

- lib/http2/request.js
Added an empty line with CRLF endings to fix skipping first sent header in http2 requests. 
The bug has no effect on the actual request send, only results in missing headers being recorded in debug info
> Added empty CRLF for http2 sent headers to avoid skipping missed headers in debug info

- README.md
- lib/autohttp/request.js
- lib/http2/agent.js
- lib/http2/request.js
- request.js
- tests/test-agentIdleTimeout.js
- tests/test-errors-http2-auto-specific.js
- tests/test-errors-http2-specific.js
- tests/test-idle-timeout-http2.js
- tests/test-idle-timeout.js
* Adds and tests idle timeout functionality for HTTP2 agent
* Adds `agentIdleTimeout` option to discard agent after given number of milliseconds after last use
> Fix Auto Requests crashing after client network disconnect

- lib/autohttp/agent.js
- lib/http2/agent.js
- lib/http2/request.js
Improves the way refs are handled for HTTP/2 requests. This fixes an issue with multiple parallel `auto` requests  causing the event loop to not exit.
> Fix HTTP/2 connection refs causing event loop to not exit

- lib/har.js
- package.json
- [N/A] I have added/updated tests for any new behavior.
- [N/A] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]
This PR removes the use of the har-validator library which is no longer supported. Since the library is EOL, it poses a security concern.
> Removing deprecated har-validator library
